export const ADD_CART_LOADING = 'ADD_CART_LOADING';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_LOADING';

export const INCREASE_CART_QUANTITY = 'INCREASE_CART_QUANTITY';
export const DECREASE_CART_QUANTITY = 'DECREASE_CART_QUANTITY';

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
