export const FETCH_SINGLE_LOADING = 'FETCH_SINGLE_LOADING';
export const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
export const FETCH_SINGLE_FAILURE = 'FETCH_SINGLE_FAILURE';
export const FETCH_SINGLE_CLEAN = 'FETCH_SINGLE_CLEAN';
